apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train-scheduler
  name: train-scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-scheduler
  strategy: {}
  template:
    metadata:
      labels:
        app: train-scheduler
    spec:
      containers:
      - image: linuxacademycontent/train-schedule:autoscaling
        name: train-schedule
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 2

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: train-svc
  name: train-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 8080
  selector:
    app: train-scheduler
  type: NodePort


---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: train-scheduler-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: train-scheduler
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
